on:
  pull_request:
  push:
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3    
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
  
      - name: Run Jest tests
        run: npm test


      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    
        with:
          name: JEST Tests           
          path: reports/jest-*.xml   
          reporter: jest-junit        