on:
  pull_request:
  push:

permissions:
  contents: read
  actions: read
  checks: write
jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2    
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
  
      - name: Run Jest tests
        run: npm test
      
      - name: Create coverages
        run: npm run coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    
        with:
          name: JEST Tests           
          path: reports/jest-*.xml   
          reporter: jest-junit