name: 'coverage'
on:
    pull_request:
    push:
        branches:
            - master
            - main
permissions:
    contents: read
    actions: read
    checks: write
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                github-token: ${{ secrets.SECRET_TOKEN }}


