name: Run Tests and Publish Reports

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run Jest and generate JUnit report
      run: npm test

    - name: Archive JUnit report
      uses: actions/upload-artifact@v2
      with:
        name: junit-report
        path: ./test-results/junit

    - name: Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    
      with:
        name: JEST Tests            
        path: ./test-results/junit/jest-*.xml
        reporter: jest-junit      
        github_token: ${{ secrets.SECRET_TOKEN }}

